apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Requesting 1Gi of storage
  storageClassName: manual  # Should match the PV's storageClassName

